- check_process
- conf/nginx.conf
- conf/php-fpm.conf
- manifest.json
- scripts/backup
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- *Package out of date*
- *Package refactored to adjust to latest standards*
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.  
~*Medium decision*~
~One public package check log is enough instead of two checks.  
When the PR is mark as ready to merge, you have to wait for 7 days before really merge it.~
Since this PR has been rerouted from master to testing. It passes to a minor decision.
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.
> Refactoring

- README.md
- check_process
- conf/nginx.conf
- manifest.json
- scripts/_common.sh
- scripts/backup
- scripts/change_url
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- *to solve CI error and more*
- *And how you fix that*
---
*Minor decision*
- **Upgrade previous version** : 
- **CI succeeded** : [![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/my_webapp_ynh%20PR31%20(Official_fork)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/my_webapp_ynh%20PR31%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.
>  Apply example_ynh

- README.md
- conf/nginx.conf
- conf/php-fpm.conf
- manifest.json
- pull_request_template.md
- scripts/backup
- scripts/change_url
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- sources/www/index.html
- *Global upgrade of the package.*
---
*Minor decision*
- **Upgrade previous version** : 
- **CI succeeded** : 
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/my_webapp_ynh%20package_upgrade%20(Official)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/my_webapp_ynh%20package_upgrade%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.
> Package upgrade

- README.md
- check_process
- manifest.json
- scripts/_common.sh
- scripts/backup
- scripts/change_url
- scripts/install
- scripts/remove
- scripts/restore
- scripts/upgrade
- *Global upgrade of the package.*
---
*Minor decision*
- **Upgrade previous version** : 
- **CI succeeded** : 
[![Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/my_webapp_ynh%20PR38/badge/icon)](https://ci-apps-hq.yunohost.org/jenkins/job/my_webapp_ynh%20PR38/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.
> Normalization from example_ynh

- README.md
- README_fr.md
- manifest.json
- pull_request_template.md
- scripts/actions/sftp
- scripts/install
- scripts/upgrade
> Cleaning up

- README.md
- README_fr.md
> Fix doc links

- manifest.json
- Missa is tired of having to repeat that this app exists to users.
- Enhance visibility in the catalog by adding keywords to the description
> Add "static" and "PHP" keywords in the description

- manifest.json
> Bump package version

- scripts/install
- scripts/restore
- scripts/upgrade
Fixes #79 
Removing `others` permissions is not enough, `group` permission needs to be `r-w`.
> Force chmod 750 to ensure SFTP chroot

- manifest.json
- scripts/install
- scripts/restore
- scripts/upgrade
> Fix directory permissions for SFTP chroot

- manifest.json
I don't know you but I get confused when I try to install this app... What's it called déjà 🤔?
I suggest giving it the same name as the ID, like all other apps. (I assume the catalog entry will also need to be changed)
> Set app name logically

- check_process
- manifest.json
- scripts/install
- scripts/restore
- scripts/upgrade
Add `php-mysql` when a database is created. cf https://forum.yunohost.org/t/my-webapp-mysql-connection-failed-could-not-find-driver/20947
> Add php-mysql if the database is installed

- config_panel.toml
- scripts/_common.sh
- scripts/config
- scripts/install
- scripts/upgrade
Closes #72 
- *And how do you fix that problem*
> Config Panel 1.0

- scripts/install
> Fix PHP config settings installation

- doc/POST_INSTALL.md
- doc/POST_INSTALL_fr.md
- manifest.toml
- *Description of why you made this PR*
- *And how do you fix that problem*
> Conditional block for POST_INSTALL.md

- conf/nginx-code-error.conf
- conf/nginx.conf
- config_panel.toml
- doc/ADMIN.md
- doc/ADMIN_fr.md
- doc/DESCRIPTION.md
- doc/DESCRIPTION_fr.md
- doc/POST_INSTALL_fr.md
- manifest.toml
- scripts/backup
- scripts/change_url
- scripts/config
- scripts/install
- scripts/upgrade
This pull request provides support for 404 errors in Nginx
- Settings can be added in the application administration panel.
- Request settings during installation
> Setup 404 error code

- conf/nginx.conf
> Prioritize index.php over index.html

- config_panel.toml
- scripts/config
- *Password change from the config panel (with or without SFTP access change) was not taken into account.* #126
- *In the config panel, questions are only asked in English*
- *Fix `scripts/config`*
- *Add french questions in  `config_panel.toml`*
> Fix password change

- ALL_README.md
- README_ca.md
- README_de.md
- README_es.md
- scripts/config
- scripts/install
- scripts/upgrade
- App configuration fails as FPM is configured but not exposed via config panel - https://paste.yunohost.org/raw/hosavitiye
- Introduced by  #148 likely
- Remove all the mentions of FPM config, it's neither in config panel nor install options. Defaults are `low`, deal with it xD
> Remove FPM configuration mentions

- config_panel.toml
- #150 
- partially revert 8e0cbb31cde72cf108eb1e4f1c565007d5edb5c4 which fat-fingered it out xD
> Restore PHP version selection

- config_panel.toml
- manifest.toml
- *Description of why you made this PR*
- *And how do you fix that problem*
> Complete french translation (manifest and config_panel)

- config_panel.toml
- doc/ADMIN.md
- doc/ADMIN_fr.md
- doc/DESCRIPTION.md
- doc/DESCRIPTION_fr.md
- manifest.toml
- *Description of why you made this PR*
- *And how do you fix that problem*
> remove end of life PHP versions
